import os
import json
import asyncio
from pathlib import Path
from typing import Any, Dict, List

import httpx
import numpy as np
from openai import AsyncOpenAI
from raganything import RAGAnything, RAGAnythingConfig
from lightrag.utils import EmbeddingFunc

import tiktoken.load as tkload

# 先保存原始的 read_file
_orig_read_file = tkload.read_file

def _offline_read_file(path: str):
    # 只拦截 o200k_base 的远程 URL，改成本地读取
    if isinstance(path, str) and "openaipublic.blob.core.windows.net/encodings/o200k_base.tiktoken" in path:
        local_bpe = "/home/yjs/raganything/RAG-Anything-main/o200k_base.tiktoken"
        with open(local_bpe, "rb") as f:
            return f.read()
    # 其他路径照常走原来的逻辑
    return _orig_read_file(path)

# 打补丁：以后 load_tiktoken_bpe -> read_file 时都会走我们这个函数
tkload.read_file = _offline_read_file

# ====== Config (adjust as needed) ======
API_KEY = os.getenv("LLM_BINDING_API_KEY") or "<YOUR_API_KEY>"
BASE_URL = os.getenv("LLM_BINDING_HOST") or "https://api.bltcy.ai/v1"
# VLM 服务（本地 vLLM 转发）的 OpenAI 兼容地址
VLM_BASE_URL = os.getenv("LLM_VLM_HOST") or "http://127.0.0.1:22004/v1"
# VLM 模型名（启动 vLLM 时的名称/路径）
LLM_MODEL = os.getenv("LLM_MODEL") or "/home/yjs/robot/VLM/32B"

EMBED_MODEL = "text-embedding-3-small"
EMBED_DIM = 4096  # change if your provider uses a different dimension
# 本地 embedding 服务
EMBED_BASE_URL = os.getenv("LLM_EMBED_HOST") or "http://127.0.0.1:8808/v1"
EMBED_MODEL = os.getenv("EMBEDDING_MODEL") or "/home/yjs/robot/VLM/8Bembedding"

WORKDIR = "./rag_storage_fin1"  # isolated working dir

EVAL_PROMPT = """You are an expert evaluator tasked with assessing the accuracy of answers generated by a RAG (Retrieval-Augmented Generation) system.

**Task**: Evaluate whether the generated answer correctly responds to the given question based on the expected answer.

**Question**: {question}

**Expected Answer**: {expected_answer}

**Generated Answer**: {generated_answer}

**Evaluation Criteria**:
1. **Accuracy (0 or 1)**: Does the generated answer match the factual content of the expected answer?
   - 1: The generated answer is factually correct and aligns with the expected answer
   - 0: The generated answer is factually incorrect or contradicts the expected answer

**Instructions**:
- Focus on factual correctness, not writing style or format
- Consider partial matches: if the generated answer contains the correct information but includes additional context, it should still be considered accurate
- For numerical answers, check if the values match or are equivalent
- For list answers, check if all key elements are present
- If the expected answer is "Not answerable" and the generated answer indicates inability to answer, consider it accurate

**Output Format**:
Please respond with a JSON object containing only:
{{
  "accuracy": 0 or 1,
  "reasoning": "Brief explanation of your evaluation"
}}
"""

RAW_ROOT = Path("datasets/raw/Fin")
MINERU_ROOT = Path("datasets/mineru_output/fin")
# ======================================


def _normalize_base(url: str, path: str) -> str:
    url = url.rstrip("/")
    if url.endswith("/v1"):
        return f"{url}/{path.lstrip('/')}"
    return f"{url}/v1/{path.lstrip('/')}"


def build_rag() -> RAGAnything:
    vlm_client = AsyncOpenAI(api_key="EMPTY", base_url=VLM_BASE_URL, timeout=3600)
    embed_client = AsyncOpenAI(api_key="EMPTY", base_url=EMBED_BASE_URL, timeout=3600)

    async def chat_complete(prompt: str, system_prompt: str | None = None, **_: Any) -> str:
        messages = []
        if system_prompt:
            messages.append({"role": "system", "content": system_prompt})
        messages.append({"role": "user", "content": prompt})

        resp = await vlm_client.chat.completions.create(
            model=LLM_MODEL,
            messages=messages,
            max_tokens=2048,
            stream=False,
        )
        if not hasattr(resp, "choices") or not resp.choices:
            return str(resp)
        return resp.choices[0].message.content

    async def embedding_func_impl(texts: List[str]) -> Any:
        resp = await embed_client.embeddings.create(
            model=EMBED_MODEL,
            input=texts,
        )
        if not hasattr(resp, "data"):
            raise RuntimeError(f"Unexpected embedding response: {resp}")
        vectors: List[List[float]] = []
        for item in resp.data:
            emb = getattr(item, "embedding", None)
            if isinstance(emb, list):
                vectors.append(emb)
        return np.array(vectors, dtype=np.float32)

    embedding_func = EmbeddingFunc(
        embedding_dim=EMBED_DIM,
        max_token_size=8192,
        func=embedding_func_impl,
    )

    config = RAGAnythingConfig(
        working_dir=WORKDIR,
        parser="mineru",
        parse_method="auto",
        enable_image_processing=True,
        enable_table_processing=True,
        enable_equation_processing=True,
    )

    return RAGAnything(
        config=config,
        llm_model_func=chat_complete,
        embedding_func=embedding_func,
    )


async def load_content_list(pdf_stem: str) -> List[Dict[str, Any]]:
    """
    Load content_list; if subdir has parts (e.g., stem_part1/part2), merge them.
    """
    merged: List[Dict[str, Any]] = []

    # Find all candidate part directories matching pdf_stem*
    candidates = sorted(
        p for p in MINERU_ROOT.iterdir() if p.is_dir() and p.name.startswith(pdf_stem)
    )
    if not candidates:
        raise FileNotFoundError(f"No MinerU output found for stem: {pdf_stem}")

    for part_dir in candidates:
        cl_dir = part_dir / "cloud"
        cl_path = cl_dir / f"{pdf_stem}_content_list.json"
        if not cl_path.exists():
            # try with part-specific name
            alt = cl_dir / f"{part_dir.name}_content_list.json"
            if alt.exists():
                cl_path = alt
        if not cl_path.exists():
            continue

        with open(cl_path, "r", encoding="utf-8") as f:
            content_list = json.load(f)

        images_dir = cl_dir / "images"
        for item in content_list:
            if isinstance(item, dict) and item.get("type") == "image":
                img_path = item.get("img_path")
                if img_path and not Path(img_path).is_absolute():
                    clean_path = img_path[len("images/") :] if img_path.startswith("images/") else img_path
                    item["img_path"] = str((images_dir / clean_path).resolve())

        merged.extend(content_list)

    if not merged:
        raise FileNotFoundError(f"content_list.json not found for stem: {pdf_stem}")

    return merged


async def evaluate_answer(rag: RAGAnything, question: str, expected: str, generated: str) -> str:
    prompt = EVAL_PROMPT.format(
        question=question, expected_answer=expected, generated_answer=generated
    )
    return await rag.llm_model_func(prompt, system_prompt=None)


async def run_eval():
    rag = build_rag()
    results: List[Dict[str, Any]] = []
    result_path = Path("fin_eval_results1.jsonl")
    if result_path.exists():
        result_path.unlink()

    def _sort_key(p: Path):
        name = p.name
        return (0, int(name)) if name.isdigit() else (1, name)

    for qa_dir in sorted(RAW_ROOT.iterdir(), key=_sort_key):
        if not qa_dir.is_dir():
            continue

        pdf_files = list(qa_dir.glob("*.pdf"))
        qa_files = list(qa_dir.glob("*_qa.jsonl"))
        if not pdf_files or not qa_files:
            continue

        pdf_path = pdf_files[0]
        pdf_stem = pdf_path.stem  # e.g., 20220817
        qa_path = qa_files[0]

        # 清理工作目录，保证每个文件夹独立评测
        if Path(WORKDIR).exists():
            import shutil
            shutil.rmtree(WORKDIR, ignore_errors=True)
        Path(WORKDIR).mkdir(parents=True, exist_ok=True)

        print(f"\n=== Processing {pdf_stem} ===")
        content_list = await load_content_list(pdf_stem)

        await rag.insert_content_list(
            content_list=content_list,
            file_path=str(pdf_path),
            doc_id=pdf_stem,
            display_stats=False,
        )

        with open(qa_path, "r", encoding="utf-8") as f:
            qa_lines = [json.loads(line) for line in f]

        answered = 0
        correct = 0
        doc_results: List[Dict[str, Any]] = []

        for idx, qa in enumerate(qa_lines, 1):
            question = qa["question"]
            expected = qa["answer"]
            qtype = qa.get("type")

            # Skip meta-data type questions
            if isinstance(qtype, str) and qtype.lower() == "meta-data":
                print(f"[{pdf_stem}] Q{idx} skipped (type=meta-data)")
                continue

            generated = await rag.aquery(question, mode="mix", enable_rerank=False)
            judgement = await evaluate_answer(rag, question, expected, generated)

            # Parse accuracy from LLM judgement JSON if possible
            acc = None
            reasoning = None
            try:
                j_obj = json.loads(judgement)
                acc = int(j_obj.get("accuracy")) if "accuracy" in j_obj else None
                reasoning = j_obj.get("reasoning")
            except Exception:
                acc = None

            doc_results.append(
                {
                    "accuracy": acc,
                    "doc": pdf_stem,
                    "idx": idx,
                    "type": qtype,
                    "question": question,
                    "expected": expected,
                    "generated": generated,
                    "reasoning": reasoning,
                    "evaluation": judgement,
                }
            )
            if acc is not None:
                answered += 1
                correct += acc
            print(f"[{pdf_stem}] Q{idx} => Eval: {judgement}")
            print(f"  Expected: {expected}")
            print(f"  Generated: {generated}")
            if reasoning:
                print(f"  Reasoning: {reasoning}")

        if answered > 0:
            doc_acc = correct / answered
            print(f"[{pdf_stem}] Accuracy: {correct}/{answered} = {doc_acc:.3f}")
        else:
            print(f"[{pdf_stem}] Accuracy: N/A (no evaluated questions)")

        # Append this document's results to global list and file
        results.extend(doc_results)
        with result_path.open("a", encoding="utf-8") as f:
            for r in doc_results:
                f.write(json.dumps(r, ensure_ascii=False) + "\n")
        print(f"[{pdf_stem}] Results appended to {result_path}")

    print("\n===== Evaluation Done =====")
    for r in results:
        print(
            f"{r['doc']} Q{r['idx']} | Expected: {r['expected']} | "
            f"Generated: {r['generated'][:80]}... | Eval: {r['evaluation']}"
        )

    print(f"\nAll results saved to {result_path}")


if __name__ == "__main__":
    asyncio.run(run_eval())
