"""
Run QA over processed MinerU documents and evaluate answers with GPT-4o-mini.

Loads a JSON file of questions and expected answers, queries RAG-Anything for each
question, then asks the model to judge correctness using the provided evaluation prompt.
"""
#测评全流程的主代码
from __future__ import annotations

import argparse
import asyncio
import json
import os
import shutil
import sys
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Tuple

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))

from lightrag.llm.openai import openai_complete_if_cache  # type: ignore  # noqa: E402

from raganything.auto_thinking import (  # noqa: E402
    ComplexityClassifier,
    HybridRAGOrchestrator,
    QuestionDecomposer,
    VLMClient,
)
from raganything.hypergraph import HyperGraphRAG  # noqa: E402
from raganything.hypergraph.llm import (  # noqa: E402
    openai_embedding,
    qwen3_embedding,
)  # noqa: E402
from raganything.hypergraph.utils import EmbeddingFunc  # noqa: E402
from raganything.utils import separate_content  # noqa: E402
from scripts.ingest_mineru_academic import (  # noqa: E402
    build_rag_instance,
    gather_content_for_doc,
)

DEFAULT_API_KEY = "REPLACE_WITH_SILICONFLOW_API_KEY"

EVAL_PROMPT = """You are an expert evaluator tasked with assessing the accuracy of answers generated by a RAG (Retrieval-Augmented Generation) system.

**Task**: Evaluate whether the generated answer correctly responds to the given question based on the expected answer.

**Question**: {question}

**Expected Answer**: {expected_answer}

**Generated Answer**: {generated_answer}

**Evaluation Criteria**:
1. **Accuracy (0 or 1)**: Does the generated answer match the factual content of the expected answer?
   - 1: The generated answer is factually correct and aligns with the expected answer
   - 0: The generated answer is factually incorrect or contradicts the expected answer

**Instructions**:
- Focus on factual correctness, not writing style or format
- Consider partial matches: if the generated answer contains the correct information but includes additional context, it should still be considered accurate
- For numerical answers, check if the values match or are equivalent
- For list answers, check if all key elements are present
- If the expected answer is "Not answerable" and the generated answer indicates inability to answer, consider it accurate

**Output Format**:
Please respond with a JSON object containing only:
{{
  "accuracy": 0 or 1,
  "reasoning": "Brief explanation of your evaluation"
}}
"""


def detect_document_info(question_file: Path) -> Tuple[str, Path]:
    """Locate the source PDF and derive doc_id for a question file."""
    pdfs = sorted(question_file.parent.glob("*.pdf"))
    if not pdfs:
        raise ValueError(f"No PDF found alongside {question_file}")
    if len(pdfs) > 1:
        print(
            f"Warning: multiple PDFs found near {question_file}. "
            f"Using {pdfs[0].name}"
        )
    pdf_path = pdfs[0]
    return pdf_path.stem, pdf_path


def parse_json_questions(path: Path) -> List[Dict[str, Any]]:
    """Parse questions from a JSON file."""
    doc_id, pdf_path = detect_document_info(path)
    data = json.loads(path.read_text(encoding="utf-8"))
    if isinstance(data, dict):
        items = (
            data.get("questions")
            or data.get("items")
            or data.get("qa")
            or data.get("data")
            or []
        )
    elif isinstance(data, list):
        items = data
    else:
        raise ValueError(f"Unsupported JSON format in {path}")
    questions: List[Dict[str, Any]] = []
    for idx, item in enumerate(items):
        question = item.get("question")
        expected = item.get("answer") or item.get("expected_answer") or ""
        if not question:
            raise ValueError(f"Missing 'question' field at index {idx}")
        questions.append(
            {
                "id": item.get("id", idx),
                "question": question,
                "expected": expected,
                "source": str(path),
                "type": item.get("type", ""),
                "doc_id": doc_id,
                "pdf_path": str(pdf_path),
            }
        )
    return questions


def parse_jsonl_questions(path: Path) -> List[Dict[str, Any]]:
    """Parse questions from a JSONL file (one JSON object per line)."""
    doc_id, pdf_path = detect_document_info(path)
    questions: List[Dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as f:
        for idx, line in enumerate(f):
            line = line.strip()
            if not line:
                continue
            try:
                item = json.loads(line)
            except json.JSONDecodeError as exc:  # noqa: PERF203
                raise ValueError(f"Invalid JSON on line {idx + 1} in {path}") from exc
            question = item.get("question")
            expected = item.get("answer") or item.get("expected_answer") or ""
            if not question:
                raise ValueError(f"Missing 'question' field on line {idx + 1} in {path}")
            questions.append(
                {
                    "id": item.get("id", idx),
                    "question": question,
                    "expected": expected,
                    "source": f"{path}:{idx + 1}",
                    "type": item.get("type", ""),
                    "doc_id": doc_id,
                    "pdf_path": str(pdf_path),
                }
            )
    return questions


def load_questions(target: Path) -> List[Dict[str, Any]]:
    """Load questions from a JSON/JSONL file or directory containing such files."""
    if target.is_file():
        return parse_questions_file(target)

    if not target.is_dir():
        raise ValueError(f"Provided path is neither file nor directory: {target}")

    questions: List[Dict[str, Any]] = []
    for file_path in sorted(target.rglob("*")):
        if file_path.suffix.lower() in {".json", ".jsonl"}:
            questions.extend(parse_questions_file(file_path))
    if not questions:
        raise ValueError(f"No JSON/JSONL question files found under {target}")
    return questions


def parse_questions_file(path: Path) -> List[Dict[str, Any]]:
    suffix = path.suffix.lower()
    if suffix == ".json":
        return parse_json_questions(path)
    if suffix == ".jsonl":
        return parse_jsonl_questions(path)
    raise ValueError(f"Unsupported question file type: {path}")


async def call_evaluator(
    question: str,
    expected: str,
    generated: str,
    api_config: dict | None = None,
) -> Dict[str, Any]:
    api_cfg = api_config or {}
    api_key = (
        api_cfg.get("api_key")
        or os.getenv("BLTCY_API_KEY")
        or os.getenv("LLM_BINDING_API_KEY")
        or DEFAULT_API_KEY
    )
    if not api_key or api_key.startswith("REPLACE_WITH"):
        raise RuntimeError("DEFAULT_API_KEY is not set. Please edit scripts/run_qa_eval.py.")
    base_url = api_cfg.get("chat_host") or os.getenv(
        "LLM_BINDING_HOST", "https://api.siliconflow.cn/v1"
    )
    eval_model = api_cfg.get("model") or os.getenv("EVAL_MODEL") or "Qwen/Qwen2.5-VL-72B-Instruct"
    prompt = EVAL_PROMPT.format(
        question=question,
        expected_answer=expected or "Not provided",
        generated_answer=generated or "No answer",
    )
    response = openai_complete_if_cache(
        eval_model,
        prompt,
        api_key=api_key,
        base_url=base_url,
    )
    if asyncio.iscoroutine(response):
        response = await response
    return parse_eval_response(response)


def parse_eval_response(text: str) -> Dict[str, Any]:
    raw = text.strip()

    def try_parse(candidate: str) -> Dict[str, Any] | None:
        # Clean up common LaTeX escape sequences (e.g., \( \)) that break JSON parsing
        cleaned = candidate.replace("\\(", "(").replace("\\)", ")")
        cleaned = cleaned.replace("\\[", "[").replace("\\]", "]")
        try:
            return json.loads(cleaned)
        except json.JSONDecodeError:
            return None

    data: Dict[str, Any] | None = None

    # Prefer extracting JSON object from fenced code blocks, tolerating language tags like ```json
    if "```" in raw:
        parts = raw.split("```")
        for part in parts:
            p = part.strip()
            if not p:
                continue
            # Find JSON object boundaries within the part
            start = p.find("{")
            end = p.rfind("}")
            if start != -1 and end != -1 and end > start:
                candidate = p[start : end + 1]
                data = try_parse(candidate)
                if data is not None:
                    break

    # Fallback: extract JSON object from the raw string even without fences
    if data is None:
        start = raw.find("{")
        end = raw.rfind("}")
        if start != -1 and end != -1 and end > start:
            candidate = raw[start : end + 1]
            data = try_parse(candidate)
        else:
            data = try_parse(raw)

    if data is None:
        raise ValueError(f"Failed to parse evaluator response:\n{raw}")

    accuracy = data.get("accuracy")
    reasoning = data.get("reasoning") or data.get("explanation") or ""

    # Normalise accuracy to 0/1
    if isinstance(accuracy, bool):
        accuracy = 1 if accuracy else 0
    elif isinstance(accuracy, str):
        try:
            accuracy = int(accuracy)
        except ValueError:
            pass

    if accuracy not in (0, 1):
        raise ValueError(f"Invalid accuracy in evaluator response: {data}")

    return {"accuracy": int(accuracy), "reasoning": str(reasoning)}


def build_orchestrator(
    light_dir: Path,
    hyper_dir: Path,
    api_config: dict | None = None,
    *,
    enable_multi_step: bool = False,
    max_sub_questions: int = 4,
    max_parallel_subqueries: int = 3,
) -> HybridRAGOrchestrator:
    api_cfg = api_config or {}
    rag = build_rag_instance(str(light_dir), api_config=api_cfg)
    config = rag.config
    config.enable_auto_thinking = True

    api_key = api_cfg.get("api_key") or config.bltcy_api_key or DEFAULT_API_KEY
    if not api_key or api_key == "REPLACE_WITH_API_KEY" or api_key == "REPLACE_WITH_SILICONFLOW_API_KEY":
        raise RuntimeError("DEFAULT_API_KEY is not set. Please edit scripts/run_qa_eval.py.")

    chat_host = api_cfg.get("chat_host") or os.getenv(
        "LLM_BINDING_HOST", "https://api.siliconflow.cn/v1"
    )
    embed_host = api_cfg.get("embed_host") or os.getenv("EMBEDDING_BINDING_HOST", chat_host)
    model_name = api_cfg.get("model") or config.bltcy_model or os.getenv(
        "BLTCY_MODEL", "Qwen/Qwen2.5-VL-72B-Instruct"
    )
    chat_api_base = api_cfg.get("chat_api_base") or config.bltcy_api_base

    embed_model = api_cfg.get("embed_model") or os.getenv(
        "EMBEDDING_MODEL", "/home/yjs/robot/VLM/8Bembedding"
    )

    hyper_embedding = EmbeddingFunc(
        embedding_dim=4096,
        max_token_size=8192,
        func=lambda texts: qwen3_embedding(
            texts,
            api_key=os.getenv("QWEN_EMBEDDING_API_KEY") or api_key,
            base_url=embed_host,
            model=embed_model,
        ),
    )
    hyper = HyperGraphRAG(
        working_dir=str(hyper_dir),
        embedding_func=hyper_embedding,
        embedding_batch_num=8,
        llm_model_kwargs={
            "api_key": api_key,
            "api_base": chat_api_base,
            "model": "qwen3-8b",
        },
    )

    auto_think_model = os.getenv("AUTO_THINK_MODEL", "qwen2.5-3b-instruct")
    auto_think_api_base = os.getenv("AUTO_THINK_API_BASE") or chat_api_base
    auto_think_api_key = os.getenv("AUTO_THINK_API_KEY") or api_key

    vlm_client = VLMClient(
        api_key=auto_think_api_key,
        api_base=auto_think_api_base or "https://api.bltcy.ai/v1/chat/completions",
        model=auto_think_model,
        timeout=720.0,
    )

    classifier = ComplexityClassifier(vlm_client)
    decomposer = QuestionDecomposer(
        vlm_client,
        max_sub_questions=max_sub_questions,
    )

    orchestrator = HybridRAGOrchestrator(
        rag,
        hyper,
        classifier=classifier,
        vlm_client=vlm_client,
        sync_mode=config.auto_thinking_sync_mode,
        chunk_token_size=config.hyper_chunk_token_size,
        chunk_overlap=config.hyper_chunk_overlap,
        decomposer=decomposer,
        enable_multi_step=enable_multi_step,
        max_parallel_subqueries=max_parallel_subqueries,
    )
    return orchestrator


async def run_evaluation(
    question_file: Path,
    mineru_root: Path,
    output_path: Path | None = None,
    detail_log_path: Path | None = None,
    folder_name: str | None = None,
    api_config: dict | None = None,
    detail_log_lock: asyncio.Lock | None = None,
    *,
    enable_multi_step: bool = False,
    max_sub_questions: int = 4,
    max_parallel_subqueries: int = 3,
    show_plan: bool = False,
) -> None:
    questions = load_questions(question_file)
    base_working_dir = Path(os.getenv("WORKING_DIR", "./rag_storage")).resolve()
    token_log_path = Path(os.getenv("TOKEN_STATS_LOG", "token_stats.jsonl")).resolve()

    current_doc_id: Optional[str] = None
    current_working_dir: Optional[Path] = None
    orchestrator: Optional[HybridRAGOrchestrator] = None
    doc_ingested = False

    results = []
    correct = 0
    for idx, item in enumerate(questions):
        q = item["question"]
        expected = item["expected"]
        q_type = str(item.get("type", "") or "").lower()

        if q_type == "meta-data":
            print(f"[SKIP] ({item.get('type','')}) Q: {q}")
            continue

        doc_id = item.get("doc_id")

        if doc_id != current_doc_id:
            if orchestrator is not None:
                try:
                    orchestrator.rag.close()
                except Exception:
                    pass
            if current_working_dir is not None:
                shutil.rmtree(current_working_dir, ignore_errors=True)
            current_doc_id = doc_id
            doc_suffix = doc_id if doc_id else "default"
            current_working_dir = base_working_dir / f"doc_{doc_suffix}"
            light_dir = current_working_dir / "light"
            hyper_dir = current_working_dir / "hyper"
            shutil.rmtree(current_working_dir, ignore_errors=True)
            orchestrator = build_orchestrator(
                light_dir,
                hyper_dir,
                api_config=api_config,
                enable_multi_step=enable_multi_step,
                max_sub_questions=max_sub_questions,
                max_parallel_subqueries=max_parallel_subqueries,
            )
            await orchestrator.rag._ensure_lightrag_initialized()
            doc_ingested = False

        if doc_id and not doc_ingested and orchestrator is not None:
            try:
                content_list, reference_pdf = gather_content_for_doc(
                    mineru_root.resolve(), doc_id
                )

                await orchestrator.rag.insert_content_list(
                    content_list=content_list,
                    file_path=reference_pdf,
                    doc_id=doc_id,
                    display_stats=False,
                )

                text_content, multimodal_items = separate_content(content_list)
                await orchestrator._collect_hyper_chunks(
                    doc_id,
                    text_content=text_content,
                    multimodal_items=multimodal_items,
                    file_path=reference_pdf,
                )

                doc_ingested = True
            except FileNotFoundError as exc:
                print(f"Warning: {exc}")
            except Exception as exc:
                print(f"Warning: Failed to ingest {doc_id}: {exc}")

        if orchestrator is None:
            raise RuntimeError("Hybrid orchestrator not initialised before querying.")

        query_result = await orchestrator.query(
            q,
            doc_id=doc_id,
            content_root=str(mineru_root),
        )
        answer = query_result.get("answer", "")
        route = query_result.get("source", "unknown")
        details = query_result.get("details") or {}
        sub_plan = details.get("sub_plan")
        sub_answers = details.get("sub_answers")
        synthesis = details.get("final_synthesis")
        retrieval_strategy = query_result.get("retrieval_strategy") or {}

        eval_result = await call_evaluator(q, expected, answer, api_config=api_config)
        accuracy = eval_result["accuracy"]
        if accuracy:
            correct += 1

        token_stats = None
        if token_log_path.exists():
            try:
                last_line = ""
                with token_log_path.open("r", encoding="utf-8") as tf:
                    for line in tf:
                        if line.strip():
                            last_line = line
                if last_line:
                    token_stats = json.loads(last_line)
            except Exception:
                token_stats = None

        record = {
            "id": item["id"],
            "question": q,
            "expected_answer": expected,
            "generated_answer": answer,
            "source": item.get("source"),
            "type": item.get("type"),
            "doc_id": doc_id,
            "pdf_path": item.get("pdf_path"),
            "accuracy": accuracy,
            "reasoning": eval_result["reasoning"],
            "routing": route,
            "details": details,
            "retrieval_strategy": retrieval_strategy,
            "token_stats": token_stats,
        }
        if sub_plan:
            record["sub_plan"] = sub_plan
        if sub_answers:
            record["sub_answers"] = sub_answers
        if synthesis:
            record["final_synthesis"] = synthesis
        results.append(record)
        print(
            f"[{accuracy}] ({item.get('type','')}) route={route} retrieval={retrieval_strategy or 'default'} Q: {q}\n"
            f"Expected: {expected}\nGenerated: {answer}\nReason: {eval_result['reasoning']}\n---"
        )
        if show_plan and sub_plan:
            print("Sub-question plan:")
            for sub in sub_plan.get("sub_questions", []):
                sid = sub.get("id")
                sq_text = sub.get("question")
                rationale = sub.get("rationale")
                print(f"  - {sid}: {sq_text} ({rationale or 'no rationale'})")
            if sub_answers:
                print("Intermediate answers:")
                for ans in sub_answers:
                    print(
                        f"    * {ans.get('id')}: source={ans.get('source')} "
                        f"conf={ans.get('confidence')} ans={ans.get('answer')} "
                        f"retrieval={ans.get('retrieval_strategy', 'default')}"
                    )
            if synthesis:
                print(f"Synthesised confidence: {synthesis.get('confidence')}, reasoning: {synthesis.get('reasoning')}")

        if detail_log_path and folder_name is not None:
            detail_log_path.parent.mkdir(parents=True, exist_ok=True)
            q_type = str(item.get("type", "") or "")
            detail_entry = {
                "folder": folder_name,
                "question_id": item.get("id", idx),
                "type": q_type,
                "result": "correct" if accuracy else "wrong",
            }
            payload = json.dumps(detail_entry, ensure_ascii=False)
            if detail_log_lock:
                async with detail_log_lock:
                    with detail_log_path.open("a", encoding="utf-8") as detail_file:
                        detail_file.write(payload + "\n")
            else:
                with detail_log_path.open("a", encoding="utf-8") as detail_file:
                    detail_file.write(payload + "\n")

    total = len(results)
    accuracy_rate = correct / total if total else 0.0
    print(f"\nEvaluated {total} questions. Accuracy: {accuracy_rate:.2%}")

    if orchestrator is not None:
        try:
            orchestrator.rag.close()
        except Exception:
            pass
    if current_working_dir is not None:
        shutil.rmtree(current_working_dir, ignore_errors=True)

    if output_path:
        output_path.write_text(json.dumps(results, ensure_ascii=False, indent=2), encoding="utf-8")
        print(f"Detailed results written to {output_path}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run QA and evaluate answers with GPT-4o-mini.")
    parser.add_argument("questions", type=Path, help="Path to JSON file containing questions and expected answers.")
    parser.add_argument(
        "--output",
        type=Path,
        help="Optional path to write detailed evaluation results (JSON).",
    )
    parser.add_argument(
        "--mineru-root",
        type=Path,
        default=Path("data/mineru_output/aca_prepared"),
        help="Root directory containing MinerU content_list outputs (default: data/mineru_output/aca_prepared).",
    )
    parser.add_argument(
        "--detail-log",
        type=Path,
        help="Optional JSONL file to append per-question results.",
    )
    parser.add_argument(
        "--multi-step",
        action="store_true",
        help="Enable query decomposition + multi-step retrieval for complex questions (default: on).",
    )
    parser.add_argument(
        "--no-multi-step",
        dest="multi_step",
        action="store_false",
        help="Disable query decomposition + multi-step retrieval.",
    )
    parser.add_argument(
        "--max-sub-questions",
        type=int,
        default=4,
        help="Maximum number of sub-questions to generate per query when multi-step is enabled.",
    )
    parser.add_argument(
        "--max-sub-parallel",
        type=int,
        default=3,
        help="Maximum number of sub-questions to run in parallel.",
    )
    parser.add_argument(
        "--show-plan",
        action="store_true",
        help="Print the generated sub-question plan and intermediate answers for debugging.",
    )
    parser.set_defaults(multi_step=True)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if not args.questions.exists():
        raise SystemExit(f"Questions file not found: {args.questions}")

    mineru_root = args.mineru_root
    if not mineru_root.exists():
        raise SystemExit(f"MinerU root directory not found: {mineru_root}")

    folder_name = args.questions.parent.name
    asyncio.run(
        run_evaluation(
            args.questions,
            mineru_root,
            args.output,
            args.detail_log,
            folder_name,
            enable_multi_step=args.multi_step,
            max_sub_questions=args.max_sub_questions,
            max_parallel_subqueries=args.max_sub_parallel,
            show_plan=args.show_plan,
        )
    )


if __name__ == "__main__":
    main()
